export const chatStore = {
    SET_CHATS: "SET_CHATS",
    ADD_NEW_CHATS: "ADD_NEW_CHATS",
    SET_SEARCH_VALUE_CHAT: "SET_SEARCH_VALUE_CHAT", 
    UPDATE_STATUS_ONLINE_PERSON_CHAT: "UPDATE_STATUS_ONLINE_PERSON_CHAT",
    UPDATE_STATUS_ONLINE_ALL_PERSON_CHAT: "UPDATE_STATUS_ONLINE_ALL_PERSON_CHAT",
};