export const peopleStore = {
    SET_PEOPLES: "SET_PEOPLES",
    ADD_NEW_PEOPLES: "ADD_NEW_PEOPLES",
    SET_SEARCH_VALUE_PEOPLE: "SET_SEARCH_VALUE_PEOPLE", 
    UPDATE_STATUS_ONLINE_PERSON: "UPDATE_STATUS_ONLINE_PERSON",
    UPDATE_STATUS_ONLINE_ALL_PERSON_PEOPLE: "UPDATE_STATUS_ONLINE_ALL_PERSON_PEOPLE",
};